[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2018"

[dev-dependencies]
cmd_lib = { path = ".." }
rayon = "1.5"
structopt = "0.3"
byte-unit = "4.0"

[[example]]
name = "dd_test"
path = "dd_test.rs"
